name = "fh-user-mgmt"
main = "src/index.ts"
compatibility_date = "2024-01-17"


[[services]]
binding = "sessionService"
service = "fh-session-state"

[[d1_databases]]
binding = "usersDB"
database_name = "fh-users"
database_id = "c6084208-65ec-4e59-9d51-375142f27ccc"

[vars]
EMAIL_FROM = "noreply@justblackmagic.com"
EMAIL_FROM_NAME = "Black Magic Consulting"

EMAIL_DKIM_SELECTOR = "mailchannels"
EMAIL_DKIM_DOMAIN = "justblackmagic.com"
FORGOT_PASSWORD_URL = "https://account-pages.tools.justblackmagic.com/forgot-password-reset.html"
TOKEN_VALID_MINUTES = 60

[dev]
port = 51512
